name = "deployment-check-worker"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[[workflows]]
name = "DEPLOYMENT_CHECK_WORKFLOW"
class_name = "DeploymentCheckWorkflow"

[env.production]
name = "deployment-check-worker"
